#!/bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export HOME=/root

mount /proc
mount /sys

for dev in /dev/mtdblock[1-7]; do
    if [ -b $dev ]; then
        mntpoint=`blkid -o export ${dev}| grep LABEL | cut -d "=" -f 2`
        mkdir -p /mnt/$mntpoint
        mount -t ext2 ${dev} /mnt/${mntpoint}
    fi
done

ifconfig lo 127.0.0.1

cd $HOME

cmd=$(echo $1 | cut -d " " -f1)

if [ -x "$1" ]; then
	/bin/sh -c "$*"
else
	setsid sh -c 'exec sh < /dev/hvc0 > /dev/hvc0 2>&1'
fi

for dev in /dev/mtdblock[1-7]; do
    if [ -b $dev ]; then
        umount $dev
    fi
done

mount -o ro,remount /

poweroff -f
