#!/bin/sh

# Copyright 2019 Cartesi Pte. Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/opt/cartesi/bin
DEFAULT_ENV_FILE="/etc/environment"

mount /proc
mount /sys

for dev in /dev/mtdblock[1-7]; do
    if [ -b $dev -a "$(blkid -s TYPE -o value $dev)" = "ext2" ]; then
        mtdblock=`basename $dev`
        mntpoint=`cat /sys/block/${mtdblock}/device/name`
        mkdir -p /mnt/$mntpoint
        mount -t ext2 /dev/${mtdblock} /mnt/${mntpoint}
    fi
done

/bin/busybox hostname -F /etc/hostname
/sbin/ifconfig lo 127.0.0.1

if [ -n "$*" ]; then
    export HOME=/
    export PS1='\h:\w # '
    if [ -f "$DEFAULT_ENV_FILE" ]; then
        source $DEFAULT_ENV_FILE
    fi
    setsid cttyhack /bin/sh -c "$*"
else
    echo "Nothing to do."
fi


for dev in /dev/mtdblock[1-7]; do
    if [ -b $dev -a "$(blkid -s TYPE -o value $dev)" = "ext2" ]; then
        umount $dev
    fi
done

mount -o ro,remount /

poweroff -f
